BtaPresentationWeb/Models/ErrorViewModel.cs
namespace BtaPresentationWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

BtaPresentationWeb/Models/Todo/TodoItemAddViewModel.cs
using System.ComponentModel.DataAnnotations;
using BtaApplication.Todo.Dtos;
using BtaDomain.ToDo;

namespace BtaPresentationWeb.Models.Todo
{
    public class TodoItemAddViewModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Name is required!")]
        public string Name { get; set; }

        [Range((int)TodoPriority.Low, (int)TodoPriority.High)]
        public int PriorityId { get; set; }

        public TodoItemDto ToDto()
        {
            return new TodoItemDto()
            {
                Name = Name,
                Priority = new NameIdDto(PriorityId, ((TodoPriority)PriorityId).ToString())
            };
        }
    }
}

BtaPresentationWeb/Models/Todo/TodoItemEditViewModel.cs
using System.ComponentModel.DataAnnotations;
using BtaApplication.Todo.Dtos;
using BtaDomain.ToDo;

namespace BtaPresentationWeb.Models.Todo
{
    public class TodoItemEditViewModel : TodoItemAddViewModel
    {
        [Required(ErrorMessage = "Id is required!")]
        public int Id { get; set; }

        public int StatusId { get; set; }
        
        public string StatusName => ((TodoStatus)StatusId).ToString();

        public TodoItemDto ToDto()
        {
            var dto = base.ToDto();

            dto.Id = Id;
            dto.Status = new NameIdDto(StatusId, ((TodoStatus)StatusId).ToString());
        
            return dto;
        }

        public static TodoItemEditViewModel FromDto(TodoItemDto dto)
        {
            return new TodoItemEditViewModel()
            {
                Id = dto.Id,
                Name = dto.Name,
                PriorityId = dto.Priority.Id,
                StatusId = dto.Status.Id
            };
        }
    }
}

BtaPresentationWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BtaPresentationWeb.Models;

namespace BtaPresentationWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

BtaPresentationWeb/Controllers/TodoController.cs
using BtaApplication.Todo.Mapping;
using BtaApplication.Todo.Services;
using BtaDomain.Common;
using BtaDomain.ToDo;
using BtaPresentationWeb.Models;
using BtaPresentationWeb.Models.Todo;
using Microsoft.AspNetCore.Mvc;


namespace BtaPresentationWeb.Controllers
{
    public class TodoController : Controller
    {
        private readonly ITodoItemApplicationService _todoItemService;
        
        public TodoController(ITodoItemApplicationService todoItemService)
        {
            _todoItemService = todoItemService;
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var result = _todoItemService.GetById(id);

            if (!result.IsOk)
            {
                return View("Error404");
            }

            return View(TodoItemEditViewModel.FromDto(result.Data.ToDto()));
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View("Add", new TodoItemAddViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddSave(TodoItemAddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", model);
            }

            OperationResult result = _todoItemService.Add(model.ToDto().ToEntity());

            if (!result.IsOk)
            {
                ModelState.AddModelError("AddFailed", result.ErrorMessage);
                return View("Add", model);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSave(TodoItemEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Detail", model);
            }
            
            var entity = _todoItemService.GetById(model.Id);

            if (!entity.IsOk)
            {
                return View("Error404");
            }

            OperationResult result = _todoItemService.Edit(model.ToDto().ToEntity());

            if (!result.IsOk)
            {
                ModelState.AddModelError("EditFailed", result.ErrorMessage);
                return View("Detail", model);
            }

            return RedirectToAction("Detail", new { id = model.Id });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var entity = _todoItemService.GetById(id);

            if (!entity.IsOk)
            {
                return View("Error404");
            }
            
            OperationResult result = _todoItemService.Delete(id);

            if (!result.IsOk)
            {
                ModelState.AddModelError("DeleteFailed", result.ErrorMessage);
                return View("Detail", TodoItemEditViewModel.FromDto(entity.Data.ToDto()));
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult ChangeStatus(int id, int status)
        {
            _ = _todoItemService.ChangeStatus(id, (TodoStatus)status);

            return RedirectToAction("Detail", new { id });
        }
    }
} 

BtaPresentationWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>This application was created as coding experiance presentation of ASP.NET senior developer Darina Adamec for Bayclays company.</p>

BtaPresentationWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "TODO application";
}
<div class="text-center">
    <h1 class="display-4">Welcome in TODO application</h1>
    
    <section>
        @Html.Partial("~/Views/Todo/_TodoList.cshtml")
    </section>
</div>

BtaPresentationWeb/Views/Shared/Error404.cshtml
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">Error 404.</h1>
<h2 class="text-danger">Page not found.</h2>

<div class="row">
    <div class="col">
        <a asp-action="Index" asp-controller="Home">Go home</a>
    </div>
</div>

BtaPresentationWeb/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Options
@using BtaPresentationWeb.Helpers.Configuration
@inject IOptions<BasicSettings> BasicSettings
@{
    var settings = BasicSettings.Value;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - @settings.CompanyName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/BtaPresentationWeb.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@settings.ApplicationName</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - @settings.ApplicationName - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BtaPresentationWeb/Views/Todo/Add.cshtml
@using BtaApplication.Todo.Services
@using Microsoft.AspNetCore.Mvc.TagHelpers
   
@inject ITodoItemApplicationService TodoItemApplicationService

@model BtaPresentationWeb.Models.Todo.TodoItemAddViewModel
@{
    ViewData["Title"] = "TODO Add new";

    var modelState = ViewContext.ViewData.ModelState;
}
<div class="text-center">
    <h1 class="display-4">TODO Add new</h1>
   
    <form asp-controller="Todo" asp-action="AddSave" method="post">
        <div class="row">
            <div class="col text-end">
                <a asp-action="Index" asp-controller="Home">Go home</a>
            </div>
        </div>
       @if (!modelState.IsValid)
       {
           <div class="alert alert-danger" role="alert">
               @foreach (var error in modelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage))
               {
                   <div>@error</div>
               }
           </div>
       }
       <div class="row">
           <div class="col">
               @Html.TextBoxFor(m => m.Name, new { placeholder = "Name", ariaLabel = "Name", @class = "form-control", autocomplete = "off" })
               @Html.ValidationMessageFor(m => m.Name)
           </div>
           <div class="col">
               @Html.DropDownListFor(m => m.PriorityId, TodoItemApplicationService.GetTodoPriorityDataSource(), new { @class = "form-select" })
               @Html.ValidationMessageFor(m => m.PriorityId)
           </div>
       </div>
       <div class="row">
           <div class="col text-end">
               <button type="submit" class="btn btn-primary">Save</button>
           </div>
       </div>
    </form>
</div>

BtaPresentationWeb/Views/Todo/Detail.cshtml
@using BtaApplication.Todo.Services
@using BtaDomain.ToDo
@using Microsoft.AspNetCore.Mvc.TagHelpers

@inject ITodoItemApplicationService TodoItemApplicationService

@model BtaPresentationWeb.Models.Todo.TodoItemEditViewModel
@{
    ViewData["Title"] = "TODO Detail";
    bool editable = TodoItemApplicationService.IsEditable(Model.ToDto());
    bool deletable = TodoItemApplicationService.IsDeletable(Model.ToDto());
    var modelState = ViewContext.ViewData.ModelState;
}
<div class="text-center">
    <h1 class="display-4">TODO Detail</h1>
    
    <form asp-controller="Todo" asp-action="EditSave" method="post">
        <div class="row">
            <div class="col text-end">
                <a asp-action="Index" asp-controller="Home">Go home</a>
            </div>
        </div>
        @if (!modelState.IsValid)
        {
           <div class="alert alert-danger" role="alert">
               @foreach (var error in modelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage))
               {
                   <div>@error</div>
               }
           </div>
        }
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.StatusId)
        <div class="row">
            <div class="col">
                @Html.TextBoxFor(m => m.Name, new { placeholder = "Name", ariaLabel = "Name", @class = "form-control", autocomplete = "off" })
               @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div class="col">
                @Html.DropDownListFor(m => m.PriorityId, TodoItemApplicationService.GetTodoPriorityDataSource(), new { @class = "form-select" })
               @Html.ValidationMessageFor(m => m.PriorityId)
            </div>
        </div>
        <div class="row">
            <div class="col">
                <span class="d-block bg-light p-3">@Html.DisplayTextFor(m => m.StatusName)</span>
            </div>
        </div>
        <div class="row">
            <div class="col text-start">
                @if (Model.StatusId == (int)TodoStatus.Notstarted)
                {
                    <a asp-action="ChangeStatus" asp-controller="Todo" asp-route-id="@Model.Id" asp-route-status="@((int)TodoStatus.InProgress)" class="btn btn-success">Start</a>
                }
                @if (Model.StatusId == (int)TodoStatus.InProgress)
                {
                    <a asp-action="ChangeStatus" asp-controller="Todo" asp-route-id="@Model.Id" asp-route-status="@((int)TodoStatus.Completed)" class="btn btn-success">Complete</a>
                }
            </div>
            <div class="col text-end">
                @if (editable)
                {
                    <button type="submit" class="btn btn-primary">Save</button>
                }
                @if (deletable)
                {
                    <a asp-action="Delete" asp-controller="Todo" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
                }
            </div>
        </div>
    </form>
</div>

BtaPresentationWeb/Views/Todo/_TodoList.cshtml
@using BtaApplication.Todo.Services
@model IList<BtaApplication.Todo.Dtos.TodoItemDto>

@inject ITodoItemApplicationService TodoItemApplicationService

<div class="row">
    <div class="col">
        <todo-table Items="@TodoItemApplicationService.GetList()"></todo-table>
    </div>
</div>

<div class="row">
    <div class="col text-end"><a asp-action="Add" asp-controller="Todo" class="btn btn-primary">Add new</a></div>
</div>